name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.21.3'

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install g++-10 gcc-10
      
      - name: Download and Install Build Wrapper
        run: |
          mkdir tools
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip -d tools

      - name: Build project with build-wrapper
        run: |
          tools/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output cmake -S . -B build
          tools/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          sonar-scanner \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=. \
            -Dsonar.exclusions="**/tests/**"
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.host.url=https://sonarcloud.io
